### ISSUE TITLE
Support icc profile

### ISSUE THREAD

**Issue by erikogabrielsson** [Bayer-Group/tiffslide#82]
Openslide-python has added an [`icc_profile`-property](https://github.com/openslide/openslide-python/blob/main/openslide/__init__.py#L119) that returns the icc profile as a Pillow `CmsProfile` if available. It would be nice if tiffslide could to the same. 

For aperio svs I have seen the profile in the [`InterColorProfile` tag](https://github.com/imi-bigpicture/opentile/blob/main/opentile/formats/svs/svs_tiler.py#L45). Not sure about other formats.

**Comment by ap--** [comment]
See also #11
